### ISSUE TITLE
[Suggestion[ Add as UserStyle on Stylish

### ISSUE THREAD

**Issue by charlesmilette** [MrGForse/ModernAustralis#1]
Title says it all. I'd recomment to add this style on http://userstyles.org so that Stylish users can install it.  

Don't forget to add `@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
` as first line, so that it targets only the browser.

**Comment by MrGForse** [comment]
Done and done. Thanks for the suggestion!

https://userstyles.org/styles/128209/modern-australis
